{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://140.134.79.128:40128/ (Press CTRL+C to quit)\n",
      "[2020-06-16 19:01:03,830] ERROR in app: Exception on /keynote [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-29-d8c700c43d4d>\", line 55, in hello3\n",
      "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 370, in url_for\n",
      "    return appctx.app.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2215, in handle_url_build_error\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 358, in url_for\n",
      "    endpoint, values, method=method, force_external=external\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py\", line 2020, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg'. Did you mean 'hello' instead?\n",
      "140.134.79.133 - - [16/Jun/2020 19:01:03] \"GET /keynote HTTP/1.1\" 500 -\n",
      "[2020-06-16 19:01:04,990] ERROR in app: Exception on /keynote [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-29-d8c700c43d4d>\", line 55, in hello3\n",
      "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 370, in url_for\n",
      "    return appctx.app.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2215, in handle_url_build_error\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 358, in url_for\n",
      "    endpoint, values, method=method, force_external=external\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py\", line 2020, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg'. Did you mean 'hello' instead?\n",
      "140.134.79.133 - - [16/Jun/2020 19:01:04] \"GET /keynote HTTP/1.1\" 500 -\n",
      "[2020-06-16 19:01:05,199] ERROR in app: Exception on /keynote [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-29-d8c700c43d4d>\", line 55, in hello3\n",
      "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 370, in url_for\n",
      "    return appctx.app.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2215, in handle_url_build_error\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 358, in url_for\n",
      "    endpoint, values, method=method, force_external=external\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py\", line 2020, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg'. Did you mean 'hello' instead?\n",
      "140.134.79.133 - - [16/Jun/2020 19:01:05] \"GET /keynote HTTP/1.1\" 500 -\n",
      "[2020-06-16 19:01:05,398] ERROR in app: Exception on /keynote [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-29-d8c700c43d4d>\", line 55, in hello3\n",
      "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 370, in url_for\n",
      "    return appctx.app.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2215, in handle_url_build_error\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 358, in url_for\n",
      "    endpoint, values, method=method, force_external=external\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py\", line 2020, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg'. Did you mean 'hello' instead?\n",
      "140.134.79.133 - - [16/Jun/2020 19:01:05] \"GET /keynote HTTP/1.1\" 500 -\n",
      "[2020-06-16 19:01:05,547] ERROR in app: Exception on /keynote [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-29-d8c700c43d4d>\", line 55, in hello3\n",
      "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 370, in url_for\n",
      "    return appctx.app.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2215, in handle_url_build_error\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/helpers.py\", line 358, in url_for\n",
      "    endpoint, values, method=method, force_external=external\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py\", line 2020, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg'. Did you mean 'hello' instead?\n",
      "140.134.79.133 - - [16/Jun/2020 19:01:05] \"GET /keynote HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, jsonify, redirect, send_from_directory, request, url_for\n",
    "import  pymysql \n",
    "import json\n",
    "import datetime\n",
    "app = Flask(__name__)\n",
    "\n",
    "def myconverter(o):\n",
    "    if isinstance(o, datetime.datetime):\n",
    "        return o.__str__()\n",
    "\n",
    "def get_club_json():\n",
    "    conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='afterclasscalendar', charset='utf8')\n",
    "    cursor = conn.cursor()\n",
    "    query = \"select * from 社團\"\n",
    "    cursor.execute(query)\n",
    "    result = cursor.fetchall()\n",
    "    clubs = []\n",
    "\n",
    "    for row in result:\n",
    "        clubs.append({'id': row[0], 'name': row[1], 'type': row[2], 'office': row[3], 'session': row[4], 'teacher': row[5], 'fee': row[6], 'introduction': row[7], 'logo': row[8]})\n",
    "    return json.dumps(clubs)\n",
    "# print(json)\n",
    "\n",
    "def get_activity_json():\n",
    "    conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='root', db='afterclasscalendar', charset='utf8')\n",
    "    cursor = conn.cursor()\n",
    "    query = \"select * from 活動 order by 活動時間 desc\"\n",
    "    cursor.execute(query)\n",
    "    result = cursor.fetchall()\n",
    "    activities = []\n",
    "#     print(result)\n",
    "\n",
    "    for row in result:\n",
    "        activities.append({'id': row[0], 'name': row[1], 'time': row[2], 'location': row[3], 'fee': row[4], 'clubId': row[5], 'url': row[6]})\n",
    "#     print(activities)\n",
    "#     return json.dumps(activities)\n",
    "    return json.dumps(activities, default = myconverter)\n",
    "\n",
    "\n",
    "@app.route('/club',methods=['GET','POST'])\n",
    "def hello():\n",
    "    if request.method=='POST':\n",
    "        get_numb=request.get_data()\n",
    "        print(get_numb)\n",
    "        return get_numb\n",
    "    return get_club_json()\n",
    "\n",
    "@app.route('/activity',methods=['GET','POST'])\n",
    "def hello2():\n",
    "    if request.method=='POST':\n",
    "        return \"123\"\n",
    "    return get_activity_json()\n",
    "@app.route('/keynote',methods=['GET','POST'])\n",
    "def hello3():\n",
    "    return url_for('https://www.icloud.com/keynote/0KnGPphA7ecPzFTLC6_-orghg')\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=False, host='140.134.79.128', port='40128')\n",
    "    \n",
    "cursor.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
